schema_version = "1.0.0"

id = "meso"
version = "0.1.0"
name = "Meso Mode"
tagline = "Hold Space for a Plaza of menus, tool settings and Compass menus"
maintainer = "anoxdetox <5579531+anoxdetox@users.noreply.github.com>"
type = "add-on"

tags = ["User Interface", "3D View"]

blender_version_min = "5.2.0"

license = ["SPDX:GPL-3.0-or-later"]
